import * as vscode from "vscode";

export const DocumentFilters: Array<vscode.DocumentFilter | string> = [
  { language: "php" },
  { language: "powershell" },
  { language: "jade" },
  { language: "python" },
  { language: "r" },
  { language: "razor" },
  { language: "ruby" },
  { language: "rust" },
  { language: "scminput" },
  { language: "scss" },
  { language: "search-result" },
  { language: "shaderlab" },
  { language: "shellscript" },
  { language: "sql" },
  { language: "swift" },
  { language: "typescript" },
  { language: "vb" },
  { language: "xml" },
  { language: "yaml" },
  { language: "markdown" },
  { language: "bat" },
  { language: "clojure" },
  { language: "coffeescript" },
  { language: "jsonc" },
  { language: "c" },
  { language: "cpp" },
  { language: "csharp" },
  { language: "css" },
  { language: "dockerfile" },
  { language: "fsharp" },
  { language: "git-commit" },
  { language: "go" },
  { language: "groovy" },
  { language: "handlebars" },
  { language: "hlsl" },
  { language: "html" },
  { language: "ini" },
  { language: "java" },
  { language: "javascriptreact" },
  { language: "javascript" },
  { language: "json" },
  { language: "less" },
  { language: "log" },
  { language: "lua" },
  { language: "makefile" },
  { language: "ignore" },
  { language: "properties" },
  { language: "objective-c" },
  { language: "perl" },
  { language: "perl6" },
  { language: "typescriptreact" },
  { language: "yml" },
  "*",
];
